// <auto-generated />
using System;
using Data_Layer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data_Layer.Migrations
{
    [DbContext(typeof(LocalDBContext))]
    partial class LocalDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("Data_Layer.ECGLead", b =>
                {
                    b.Property<int>("ECGLeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ECGLeadValues")
                        .HasColumnType("BLOB");

                    b.Property<int>("ECGMeasurementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeadNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ECGLeadId");

                    b.HasIndex("ECGMeasurementId");

                    b.ToTable("ECGLeads");
                });

            modelBuilder.Entity("Data_Layer.ECGMeasurement", b =>
                {
                    b.Property<int>("ECGMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HRV")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientMeasurementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Pulse")
                        .HasColumnType("INTEGER");

                    b.HasKey("ECGMeasurementId");

                    b.HasIndex("PatientMeasurementId");

                    b.ToTable("ECGMeasurements");
                });

            modelBuilder.Entity("Data_Layer.PatientMeasurement", b =>
                {
                    b.Property<int>("PatientMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPRNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("PatientMeasurementId");

                    b.ToTable("PatientMeasurements");
                });

            modelBuilder.Entity("Data_Layer.ECGLead", b =>
                {
                    b.HasOne("Data_Layer.ECGMeasurement", "ECGMeasurement")
                        .WithMany("ECGLeads")
                        .HasForeignKey("ECGMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Data_Layer.ECGMeasurement", b =>
                {
                    b.HasOne("Data_Layer.PatientMeasurement", "PatientMeasurement")
                        .WithMany("ECGMeasurements")
                        .HasForeignKey("PatientMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
