// <auto-generated />
using System;
using LocalDatabase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LocalDatabase.Migrations
{
    [DbContext(typeof(PatientContext))]
    partial class PatientContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("LocalDatabase.ECGLead", b =>
                {
                    b.Property<int>("ECGLeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("ECGLeadValues")
                        .HasColumnType("BLOB");

                    b.Property<int>("ECGMeasurementId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LeadNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("ECGLeadId");

                    b.HasIndex("ECGMeasurementId");

                    b.ToTable("ECGLeads");
                });

            modelBuilder.Entity("LocalDatabase.ECGMeasurement", b =>
                {
                    b.Property<int>("ECGMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MeasurementNumber")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientMeasurementId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ECGMeasurementId");

                    b.HasIndex("PatientMeasurementId");

                    b.ToTable("ECGMeasurements");
                });

            modelBuilder.Entity("LocalDatabase.PatientMeasurement", b =>
                {
                    b.Property<int>("PatientMeasurementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("CPRNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("HRV")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("Pulse")
                        .HasColumnType("INTEGER");

                    b.HasKey("PatientMeasurementId");

                    b.ToTable("PatientMeasurements");
                });

            modelBuilder.Entity("LocalDatabase.ECGLead", b =>
                {
                    b.HasOne("LocalDatabase.ECGMeasurement", "ECGMeasurement")
                        .WithMany("ECGLeads")
                        .HasForeignKey("ECGMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("LocalDatabase.ECGMeasurement", b =>
                {
                    b.HasOne("LocalDatabase.PatientMeasurement", "PatientMeasurement")
                        .WithMany("ECGMeasurements")
                        .HasForeignKey("PatientMeasurementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
